### ISSUE TITLE
 Slidy example Run code does not work

### ISSUE THREAD

**Issue by RaymondBalise** [rstudio/learnr#308] opened 2019-11-17 14:37 UTC
### System details

Output of `sessioninfo::session_info()()`:

```
─ Session info ──────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Catalina 10.15.1      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-11-17                  

─ Packages ──────────────────────────────────────────────────────────────────────────
 package     * version     date       lib source                          
 assertthat    0.2.1       2019-03-21 [1] CRAN (R 3.6.0)                  
 backports     1.1.5       2019-10-02 [1] CRAN (R 3.6.0)                  
 bookdown      0.14        2019-10-01 [1] CRAN (R 3.6.0)                  
 callr         3.3.2       2019-09-22 [1] CRAN (R 3.6.0)                  
 cli           1.1.0       2019-03-19 [1] CRAN (R 3.6.0)                  
 crayon        1.3.4       2017-09-16 [1] CRAN (R 3.6.0)                  
 curl          4.2         2019-09-24 [1] CRAN (R 3.6.0)                  
 desc          1.2.0       2018-05-01 [1] CRAN (R 3.6.0)                  
 devtools    * 2.2.1       2019-09-24 [1] CRAN (R 3.6.0)                  
 digest        0.6.22      2019-10-21 [1] CRAN (R 3.6.1)                  
 dygraphs    * 1.1.1.6     2018-07-11 [1] CRAN (R 3.6.0)                  
 ellipsis      0.3.0       2019-09-20 [1] CRAN (R 3.6.0)                  
 evaluate      0.14        2019-05-28 [1] CRAN (R 3.6.0)                  
 fastmap       1.0.1       2019-10-08 [1] CRAN (R 3.6.0)                  
 fs            1.3.1       2019-05-06 [1] CRAN (R 3.6.0)                  
 glue          1.3.1       2019-03-12 [1] CRAN (R 3.6.0)                  
 highr         0.8         2019-03-20 [1] CRAN (R 3.6.0)                  
 htmltools     0.4.0       2019-10-04 [1] CRAN (R 3.6.0)                  
 htmlwidgets   1.5.1       2019-10-08 [1] CRAN (R 3.6.0)                  
 httpuv        1.5.2       2019-09-11 [1] CRAN (R 3.6.0)                  
 jsonlite      1.6         2018-12-07 [1] CRAN (R 3.6.0)                  
 knitr         1.26        2019-11-12 [1] CRAN (R 3.6.0)                  
 later         1.0.0       2019-10-04 [1] CRAN (R 3.6.0)                  
 lattice       0.20-38     2018-11-04 [1] CRAN (R 3.6.1)                  
 learnr      * 0.10.0.9000 2019-11-17 [1] Github (rstudio/learnr@1b9ac06) 
 magrittr      1.5         2014-11-22 [1] CRAN (R 3.6.0)                  
 markdown      1.1         2019-08-07 [1] CRAN (R 3.6.0)                  
 memoise       1.1.0       2017-04-21 [1] CRAN (R 3.6.0)                  
 mime          0.7         2019-06-11 [1] CRAN (R 3.6.0)                  
 packrat       0.5.0-25    2019-11-17 [1] Github (rstudio/packrat@448aafd)
 pkgbuild      1.0.6       2019-10-09 [1] CRAN (R 3.6.0)                  
 pkgload       1.0.2       2018-10-29 [1] CRAN (R 3.6.0)                  
 prettyunits   1.0.2       2015-07-13 [1] CRAN (R 3.6.0)                  
 processx      3.4.1       2019-07-18 [1] CRAN (R 3.6.0)                  
 promises      1.1.0       2019-10-04 [1] CRAN (R 3.6.0)                  
 ps            1.3.0       2018-12-21 [1] CRAN (R 3.6.0)                  
 R6            2.4.1       2019-11-12 [1] CRAN (R 3.6.0)                  
 rappdirs      0.3.1       2016-03-28 [1] CRAN (R 3.6.0)                  
 Rcpp          1.0.3       2019-11-08 [1] CRAN (R 3.6.0)                  
 remotes       2.1.0       2019-06-24 [1] CRAN (R 3.6.0)                  
 renv          0.8.3       2019-11-11 [1] CRAN (R 3.6.1)                  
 rlang         0.4.1       2019-10-24 [1] CRAN (R 3.6.1)                  
 rmarkdown     1.17        2019-11-13 [1] CRAN (R 3.6.0)                  
 rprojroot     1.3-2       2018-01-03 [1] CRAN (R 3.6.0)                  
 rstudioapi    0.10        2019-03-19 [1] CRAN (R 3.6.0)                  
 sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 3.6.0)                  
 shiny       * 1.4.0       2019-10-10 [1] CRAN (R 3.6.0)                  
 stringi       1.4.3       2019-03-12 [1] CRAN (R 3.6.0)                  
 stringr       1.4.0       2019-02-10 [1] CRAN (R 3.6.0)                  
 testthat    * 2.2.1       2019-07-25 [1] CRAN (R 3.6.0)                  
 usethis     * 1.5.1       2019-07-04 [1] CRAN (R 3.6.0)                  
 withr         2.1.2       2018-03-15 [1] CRAN (R 3.6.0)                  
 xfun          0.11        2019-11-12 [1] CRAN (R 3.6.0)                  
 xtable        1.8-4       2019-04-21 [1] CRAN (R 3.6.0)                  
 xts           0.11-2      2018-11-05 [1] CRAN (R 3.6.0)                  
 yaml          2.2.0       2018-07-25 [1] CRAN (R 3.6.0)                  
 zoo           1.8-6       2019-05-28 [1] CRAN (R 3.6.0) 
```

with 
```
Google ChromeVersion 78.0.3904.97 (Official Build) (64-bit)
```

### Example application *or* steps to reproduce the problem

```r
library(learnr)
learnr::run_tutorial("slidy", package = "learnr")
```

### Describe the problem in detail
On the second slide, the Run Code button does not work.  Pushing it, with the code provided or with 1+1, causes the output to gray out.  There are no notes/warning etc.  The page is still responsive to the arrow keys or the Start over button but the output is missing.

**Comment by schloerke** [comment] 2019-11-18 14:38
Thank you for the great bug report!!

-------------------

Hmmmmm. I can not reproduce the bug.  I have a very similar setup.

<details>
<summary>Session Info</summary>
```
❯❯ sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Catalina 10.15.1      
 system   x86_64, darwin15.6.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-11-18                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source                             
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                     
 backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.0)                     
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)                     
 clisymbols    1.2.0   2017-05-21 [1] CRAN (R 3.6.0)                     
 colorout      1.2-2   2019-09-11 [1] Github (jalvesaq/colorout@641ed38) 
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                     
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)                     
 digest        0.6.22  2019-10-21 [1] CRAN (R 3.6.1)                     
 dygraphs    * 1.1.1.6 2018-07-11 [1] CRAN (R 3.6.0)                     
 evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)                     
 fastmap       1.0.1   2019-10-08 [1] CRAN (R 3.6.0)                     
 git2r         0.26.1  2019-06-29 [1] CRAN (R 3.6.0)                     
 highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)                     
 htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)                     
 htmlwidgets   1.5.1   2019-10-08 [1] CRAN (R 3.6.0)                     
 httpuv        1.5.2   2019-09-11 [1] CRAN (R 3.6.0)                     
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.6.0)                     
 knitr         1.26    2019-11-12 [1] CRAN (R 3.6.1)                     
 later         1.0.0   2019-10-04 [1] CRAN (R 3.6.0)                     
 lattice       0.20-38 2018-11-04 [1] CRAN (R 3.6.1)                     
 learnr      * 0.10.0  2019-11-09 [1] CRAN (R 3.6.0)                     
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)                     
 markdown      1.1     2019-08-07 [1] CRAN (R 3.6.0)                     
 memuse        4.0-0   2017-11-10 [1] CRAN (R 3.6.0)                     
 mime          0.7     2019-06-11 [1] CRAN (R 3.6.0)                     
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)                     
 promises      1.1.0   2019-10-04 [1] CRAN (R 3.6.0)                     
 prompt        1.0.0   2019-05-09 [1] Github (gaborcsardi/prompt@b332c42)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)                     
 rappdirs      0.3.1   2016-03-28 [1] CRAN (R 3.6.0)                     
 Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.0)                     
 renv          0.8.3   2019-11-11 [1] CRAN (R 3.6.1)                     
 rlang         0.4.1   2019-10-24 [1] CRAN (R 3.6.1)                     
 rmarkdown     1.17    2019-11-13 [1] CRAN (R 3.6.1)                     
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)                     
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                     
 shiny       * 1.4.0   2019-10-10 [1] CRAN (R 3.6.0)                     
 stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)                     
 stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)                     
 testthat      2.3.0   2019-11-05 [1] CRAN (R 3.6.1)                     
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)                     
 xfun          0.11    2019-11-12 [1] CRAN (R 3.6.1)                     
 xtable        1.8-4   2019-04-21 [1] CRAN (R 3.6.0)                     
 xts           0.11-2  2018-11-05 [1] CRAN (R 3.6.0)                     
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)                     
 zoo           1.8-6   2019-05-28 [1] CRAN (R 3.6.0)                     

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```
</details>

Can you try again in a fresh R session and with a different browser? Can you also try it in an icognito window, please? I want to see if it was a one-off bug, something chrome specific, or something indexeddb related.

Thank you!

**Comment by RaymondBalise** [comment] 2019-11-18 21:05
It behaves if I paste the URL into Safari.  

I updated Chrome to Version 78.0.3904.108 (Official Build) (64-bit) and it still goes out to lunch in Chrome.

**Comment by schloerke** [comment] 2019-11-18 21:08
Still have issues with Chrome in an incognito window?  (Mac: `cmd + shift + n`)

**Comment by RaymondBalise** [comment] 2019-11-21 20:52
Yes.  It goes out to lunch when I push run.

**Comment by schloerke** [comment] 2019-11-21 20:58
@RaymondBalise Can you send me any screen shots of the error expanded in the developer console? (`cmd + opt + j` to load the dev console.) . 

If not, would you like to set up a video chat meeting? (email `barret@rstudio.com`) This is *really* odd as I develop with Chrome.  Thank you!

**Comment by RaymondBalise** [comment] 2019-11-23 12:11
The very first time I ran the tutorial this was in the console:
![image](https://user-images.githubusercontent.com/18148282/69478209-fe05e280-0dbd-11ea-9f7c-c132ea9d4e7e.png)

Today when I went to slide 2 I got a message that I have not seen before:
![image](https://user-images.githubusercontent.com/18148282/69478186-bbdca100-0dbd-11ea-86b3-93d95321b11a.png)

When I push the run button the code goes out to lunch but there are no notes in the console.  This happened ever time I ran learnr::run_tutorial("slidy", package = "learnr") today.

![image](https://user-images.githubusercontent.com/18148282/69478335-3b1ea480-0dbf-11ea-830d-d6b2a7c5385b.png)

I reloaded the page and the "Registered S3 method overwritten by 'xts':" message does not show up and the app behaves perfectly.  I can change the code or add new code and it just works.

![image](https://user-images.githubusercontent.com/18148282/69478451-68b81d80-0dc0-11ea-9bb3-8e4925e59297.png)

**Comment by coatless** [comment] 2019-11-23 15:07
I think this is a duplicate of #164. I believe the issue was traced back to:

> I suspect something about the way slidy_presentation handles DOM visibility and how that interacts with Shiny outputs

Unfortunately, not much was done to investigate further.

**Comment by schloerke** [comment] 2019-11-25 18:02
@coatless Yes. This seems like a duplicate.  Thank you! 🙌 

I'll give it a quick investigation, but I do not think there will be much progress here.  😞

**Comment by schloerke** [comment] 2019-11-25 22:21
👀 I can repro it using https://github.com/rstudio/learnr/issues/164#issue-330849893 . Yay!

My notes: 
* It requires RStudio as the UI.
* It requires that no exercise code has been run before.  If exercise code has been run, bump the tutorial version to continue testing
* If the slide is chosen from the beginning, it works
* The ui believes the plot output is not being displayed.  Calling `$(document.body).trigger('shown')` does not help.

Confusion:
* I don't know why the UI believes the exercise output is hidden even after calling `$(document.body).trigger('shown')`
* Using `options(shiny.trace = TRUE)` interacts poorly with `slidy` exercise UI

**Comment by schloerke** [comment] 2019-12-03 19:26
@RaymondBalise Can you please try this for me using your Chrome Browser? (The currently _broken_ browser).  I believe I have it fixed.

```r
# restart R
remotes::install_github("schloerke/rmarkdown@slidy_shiny")
# restart R, again

learnr::run_tutorial("slidy", package = "learnr")
```

**Comment by schloerke** [comment] 2019-12-03 19:28
@coatless Can you also try installing my `rmarkdown` remote and trying on your document as well? Thank you!

**Comment by coatless** [comment] 2019-12-04 16:02
@schloerke tried it out. Works like a charm. Thanks!

**Comment by schloerke** [comment] 2019-12-04 16:45
Closed in https://github.com/rstudio/rmarkdown/pull/1717

**Closed by schloerke** 2019-12-04 16:45 UTC

**Comment by RaymondBalise** [comment] 2019-12-07 21:04
I just checked and it is fixed for me also.  Thank you!
