### ISSUE TITLE
`?` shows `_` between each letter in the title of the documentation

### ISSUE THREAD

**Issue by malcolmbarrett** [rstudio/learnr#778] opened 2023-04-13 16:10 UTC
### System details

Output of `sessioninfo::session_info()()`:

```
─ Session info ────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       macOS Ventura 13.3.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Detroit
 date     2023-04-13
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)

─ Packages ────────────────────────────────────────────────────────────────────────────
 package             * version     date (UTC) lib source
 academyContentTools   0.9.3       2023-04-07 [1] local
 cachem                1.0.7       2023-02-24 [1] CRAN (R 4.2.0)
 callr                 3.7.3       2022-11-02 [1] CRAN (R 4.2.0)
 cli                   3.6.1       2023-03-23 [1] CRAN (R 4.2.0)
 crayon                1.5.2       2022-09-29 [1] CRAN (R 4.2.0)
 devtools            * 2.4.5       2022-10-11 [1] CRAN (R 4.2.0)
 digest                0.6.31      2022-12-11 [1] CRAN (R 4.2.0)
 ellipsis              0.3.2       2021-04-29 [1] CRAN (R 4.2.0)
 evaluate              0.20        2023-01-17 [1] CRAN (R 4.2.0)
 fastmap               1.1.1       2023-02-24 [1] CRAN (R 4.2.0)
 fs                  * 1.6.1       2023-02-06 [1] CRAN (R 4.2.0)
 gitcreds              0.1.2       2022-09-08 [1] CRAN (R 4.2.0)
 glue                  1.6.2       2022-02-24 [1] CRAN (R 4.2.0)
 htmltools             0.5.5       2023-03-23 [1] CRAN (R 4.2.0)
 htmlwidgets           1.6.2       2023-03-17 [1] CRAN (R 4.2.0)
 httpuv                1.6.9       2023-02-14 [1] CRAN (R 4.2.0)
 jsonlite              1.8.4       2022-12-06 [1] CRAN (R 4.2.0)
 knitr                 1.42        2023-01-25 [1] CRAN (R 4.2.0)
 later                 1.3.0       2021-08-18 [1] RSPM
 learnr                0.11.3.9000 2023-04-04 [1] local
 lifecycle             1.0.3       2022-10-07 [1] CRAN (R 4.2.0)
 magrittr              2.0.3       2022-03-30 [1] CRAN (R 4.2.0)
 memoise               2.0.1       2021-11-26 [1] RSPM
 mime                  0.12        2021-09-28 [1] CRAN (R 4.2.0)
 miniUI                0.1.1.1     2018-05-18 [1] CRAN (R 4.2.0)
 opensky             * 0.2.0       2023-01-27 [1] Github (emptyfield-ds/opensky@f9e1864)
 pak                 * 0.4.0       2023-01-15 [1] CRAN (R 4.2.0)
 pkgbuild              1.4.0       2022-11-27 [1] CRAN (R 4.2.1)
 pkgload               1.3.2       2022-11-16 [1] CRAN (R 4.2.0)
 prettyunits           1.1.1       2020-01-24 [1] CRAN (R 4.2.0)
 processx              3.8.0       2022-10-26 [1] CRAN (R 4.2.0)
 profvis               0.3.7       2020-11-02 [1] CRAN (R 4.2.0)
 promises              1.2.0.1     2021-02-11 [1] RSPM
 ps                    1.7.4       2023-04-02 [1] CRAN (R 4.2.0)
 purrr                 1.0.1       2023-01-10 [1] CRAN (R 4.2.0)
 R6                    2.5.1       2021-08-19 [1] CRAN (R 4.2.0)
 Rcpp                  1.0.10      2023-01-22 [1] CRAN (R 4.2.0)
 remotes               2.4.2       2021-11-30 [1] CRAN (R 4.2.0)
 reprex              * 2.0.2       2022-08-17 [1] CRAN (R 4.2.0)
 rlang                 1.1.0       2023-03-14 [1] CRAN (R 4.2.0)
 rmarkdown             2.21        2023-03-26 [1] CRAN (R 4.2.2)
 rprojroot             2.0.3       2022-04-02 [1] RSPM
 rsconnect             0.8.29      2023-01-09 [1] CRAN (R 4.2.0)
 rstudioapi            0.14        2022-08-22 [1] CRAN (R 4.2.0)
 selectr               0.4-2       2019-11-20 [1] CRAN (R 4.2.0)
 sessioninfo           1.2.2       2021-12-06 [1] CRAN (R 4.2.0)
 shiny                 1.7.4       2022-12-15 [1] CRAN (R 4.2.0)
 shunyata            * 0.0.1       2023-01-29 [1] local
 stringi               1.7.12      2023-01-11 [1] CRAN (R 4.2.0)
 stringr               1.5.0       2022-12-02 [1] CRAN (R 4.2.0)
 urlchecker            1.0.1       2021-11-30 [1] CRAN (R 4.2.0)
 usethis             * 2.1.6       2022-05-25 [1] CRAN (R 4.2.0)
 vctrs                 0.6.1       2023-03-22 [1] CRAN (R 4.2.0)
 withr                 2.5.0       2022-03-03 [1] RSPM
 xfun                  0.38        2023-03-24 [1] CRAN (R 4.2.0)
 xml2                  1.3.3       2021-11-30 [1] CRAN (R 4.2.0)
 xtable                1.8-4       2019-04-21 [1] RSPM
 yaml                  2.3.7       2023-01-23 [1] CRAN (R 4.2.0)
```

### Example application *or* steps to reproduce the problem

Using the learnr template, when I type `?round` I see something like

<img width="917" alt="Screenshot 2023-04-13 at 12 05 46 PM" src="https://user-images.githubusercontent.com/23123711/231820222-785cef75-09ef-4fd9-80b2-3a66e74212aa.png">

where there is `_` between every character in the title

**Comment by gadenbuie** [comment] 2023-04-13 17:05
Duplicate of #16. That's the default printing of help documentation in plain text environments.

**Closed by gadenbuie** 2023-04-13 17:05 UTC
