### ISSUE TITLE
Can I use the data from the previous chunk in the next chunk

### ISSUE THREAD

**Issue by dudrnjs1391** [rstudio/learnr#139] opened 2018-02-02 05:37 UTC
I executed this code. But, All chunk Separated and cant't inherited from previous chunk.
Can I use the data from the previous chunk to the next chunk?

* Make an Object and Check It
```
"```{r 2.1.data_create, exercise=TRUE}```"
```

```
"```{r 2.1.data_create-solution, exercise.setup="2.1.data_create-solution"}
tmp <- c(1,2,3)
```"
```

```
"```{r 2.2.data_plus, exercise=TRUE, ref.label="2.1.data_create-solution"}```"

```

```
"```{r 2.2.data_plus-solution}
tmp <- tmp+1
```"
```
### the result will be tmp = 2,3,4
<br>

```
"```{r 2.3.data_plus_plus, exercise=TRUE, ref.label="2.2.data_plus-solution"}```"
```

```
"```{r 2.3.data_plus_plus-solution}
tmp <- tmp+2
tmp
```"
```
### the result will be tmp = 4,5,6

**Comment by gadenbuie** [comment] 2021-07-09 14:19
Duplicate of #170

**Closed by gadenbuie** 2021-07-09 14:19 UTC
