### ISSUE TITLE
Add function and run_tutorial parameter to delete cached html file before running tutorial

### ISSUE THREAD

**Issue by schloerke** [rstudio/learnr#333] opened 2020-02-13 21:42 UTC
Sometimes it's nice to have a fresh state when running a tutorial.

* `reset_tutorial(name, package)`
  * Wrapper to `rmarkdown::shiny_prerendered_clean`

* `run_tutorial(name, package, ..., reset = FALSE)`
  * Add `reset = FALSE`
  * Add the `...` for "future parameter expansion" or "ignored".
  * If `isTrue(reset)` call `reset_tutorial(name, package)` before doing anything else

**Comment by matthewhirschey** [comment] 2020-04-09 14:55
This would be really helpful!
I just finished teaching a class using `learnr` and `ioslidepresentation` as an output via Rstudio.cloud. Several of the students had problems loading an object (df) after restarting the presentation. This could be fixed by selecting "Clear prerendered output". The error is likely because of the tmp directories that Rstudio.cloud uses.  (?)
Setting clear_prerendered_output:TRUE would fix this problem for early learners!

**Comment by schloerke** [comment] 2020-04-10 14:21
@matthewhirschey Couple questions...

* On Cloud, did you distribute the tutorials using an R package or the raw tutorial folder?
* Are you asking for a flag in the tutorial yaml header that could be set to **always re-render** the cached files?

**Comment by matthewhirschey** [comment] 2020-04-10 15:40
I made my own tutorials (https://github.com/matthewhirschey/tidybiology-plusds). I used learnr to embed exercises directly into the slides, and the delivered virtually.  And then I cloned the repo on an Rstudio.cloud project, which I made an assignment for students/attendees. I had the students "run document" so they could interact with the slides. 

Several of the students had a problem that a data frame object that I load this object in the first code chunk calling an R script (`heart`) could not be found. This was only upon re-rendering the slides.

If you want to try, here is a **reproducible example of the problem I encountered** 
1. clone the above repo into an Rstudio.cloud project
2. open `code/plusDS_session1.Rmd`
3. Run the document
4. Navigate to slide 14, which is the first `learnr` exercise chunk (a bit arbitrary, but this is the easiest to navigate to)
5. type `heart` to view this data frame object that I load in line 24 of that document; you should see a summary of the tibble
6. Close the window, as if you were going to navigate to another *.Rmd file, as I have the students do (but no need to open another doc)
7. Click run document again, and navigate to slide 14, and upon calling `heart`, you'll see **object not found**
8. Exit that window again, and this time, use the dropdown to 'clear pre-rendered output'
9. Run document again, and you'll see in slide 14 that you can again find the object. 

For this use case (making interactive slides), I don't need to "save progress", especially if it leads to this error. Because this is a use case, I think having a YAML flag that could always clear this output and re-render would be nice.

**Closed** 2021-12-29 17:13 UTC
Labels: difficulty: intermediate, effort: low, priority: medium, type: enhancement, help wanted
